stages:
- test
- build
- deploy

test-job:
  stage: test
  script:
  - echo "Running tests..."
  - pytest || exit 1 # Agar pytest use kar raha hai

build-job:
  stage: build
  script:
  - echo "Building project..."
  - python setup.py build || exit 1 # Agar build karna hai

deploy-job:
  stage: deploy
  script:
  - echo "Deploying project..."
  - echo "Deploy complete!"
